name: Update library

on:
  repository_dispatch:
    types: [library-published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Update library
        uses: ./.github/actions/update-library
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}